### ISSUE TITLE
Add shortcut by keycode

### ISSUE THREAD

**Issue by OwnageIsMagic** [dail8859/LuaScript#36]
For arrows, numpad keys, etc.

**Comment by dail8859** [comment]
So you mean being able to specify something like:

- "Ctrl+Alt+Up"
- "Ctrl+Alt+Num1"

**Comment by dail8859** [comment]
Digging into this looks like you can not register a shortcut with the Numpad. It shows up correctly in the menu but it never actually gets triggered when using it in Notepad++. This appears to be a bug (or maybe it is intentional) with Notepad++, but adding several of the other keycodes shouldn't be a problem.

**Comment by OwnageIsMagic** [comment]
![image](https://cloud.githubusercontent.com/assets/10534634/20197545/308de980-a7b1-11e6-916e-e6b28bafd420.png)
For me it says error in parsing
btw I can bind numpad for macros
![image](https://cloud.githubusercontent.com/assets/10534634/20197584/611655d8-a7b1-11e6-8c3a-5b7486448d57.png)

**Comment by dail8859** [comment]
> For me it says error in parsing

It's not currently set up to handle anything other than A-Z, 0-9, and F1-F12 so it definitely won't work for you.

> btw I can bind numpad for macros

Yeah but for some reason Notepad++ is treating plugin commands differently. It shows to bind in the menu but actually pressing the shortcut doesn't work.

> maybe override AddShortcut 

It's possible but that doesn't mean it will actually work (like the case of Numpad keys). Since I really don't have a good way of testing it, and personally don't have a need for it I probably won't be working on this myself but would accept a good PR adding the functionality.

**Comment by dail8859** [comment]
Considering this closed for now. I've added these additional keys:

- `;`
- `/`
- `~`
- `[`
- `\`
- `]`
- `'`
- `,`
- `-`
- `.`
- `=`
- `up`
- `down`
- `left`
- `right`
- `space`
- `pageup`
- `pagedown`
- `backspace`
- `delete`
- `escape`
