### ISSUE TITLE
Asynchronous delay like settimeout/clearTimeout function in JavaScript

### ISSUE THREAD

**Issue by computHome** [dail8859/LuaScript#51]
some action should be done in certain period of time after some event, is there any function that can be used in lua? like this in javascript

setTimeout(function() {
    savefile();
}, 5000);

**Comment by dail8859** [comment]
There isn't anything available to do something like that. AFAIK to do this would mean doing threading...which can possibly introduce a whole new set of problems.

It's a nice idea, but a proper implementation of it would be non-trivial.

**Comment by computHome** [comment]
I see. Anyway thank for the sharing of this plugin.

**Comment by dail8859** [comment]
Hi @computHome 

I've implemented a version of timer events that you are welcome to try out. I haven't updated the documentation yet as I want to make sure this works and I'm open to any suggestions you (or others) may have.

The plugin now has 2 new functions:

```lua
timer = npp.StartTimer(milliseconds, callback(timer))
```

and 

```lua
npp.StopTimer(timer)
```

These timers continuously repeat until you stop them. The callback also receives the timer so that it can be stopped inside the callback. So a trivial example may be:

```lua
-- Save a copy of the current file every 10 seconds, unless the file is too big
npp.StartTimer(10000, function(timer)
    if editor.Length < 1000 then
        npp:SaveCurrentFileAs(true, "C:\\path\\to\\current\\file.backup")
    else
        npp.StopTimer(timer)
    end
end)
```

You can download one of the zip files below (either 32 or 64 bit). Just extract it and copy over your existing `LuaScript.dll` file.

[LuaScript.zip](https://github.com/dail8859/LuaScript/files/1191474/LuaScript.zip)
[LuaScript_64.zip](https://github.com/dail8859/LuaScript/files/1191475/LuaScript_64.zip)

**Comment by dail8859** [comment]
I should also mention these timers run synchronously in the same thread as Notepad++, meaning that if Notepad++ is busy processing the file (such as doing search/replace) the timer event will get delayed. It is safe to access any of the `npp` or `editor` objects in the callback.

**Comment by computHome** [comment]
I have tried the 32-bit dll, it worked and I will report if I find any problems. Many thanks Dail
