### ISSUE TITLE
Request: Include Lua File System 

### ISSUE THREAD

**Issue by ethanpil** [dail8859/LuaScript#53]
Would you consider including Lua File System module? This way we can use the plugin to modify filesystem, generate reports, save files, etc.

https://github.com/keplerproject/luafilesystem

**Comment by dail8859** [comment]
My hope is to fix #22 as this would solve a much larger problem...that way a user could use any module they wanted (LFS, Ipelib, etc).

I do agree that LFS would be incredibly useful. If I get another chance to look into #22 and feel it is a huge challenge to solve, I *may* consider including a few"essential" modules as long as it doesn't become too burdensome.

**Comment by dail8859** [comment]
I spent some time looking into this...and building the lfs module as a static lib isn't that difficult. The biggest problem though is that I can't seem to get it to work on any paths or file names that contain any multi-byte characters since Windows uses UTF-16 character strings. I'm not sure this would have any other side effects since most of the Windows API calls wouldn't be getting UTF-16 strings.

**Comment by ethanpil** [comment]
I guess a caveat that it doesn't work is better than nothing at all... Perhaps eventually if you can solve Issue #22 then we will be able to update it or replace with something else...

**Comment by dail8859** [comment]
> I guess a caveat that it doesn't work is better than nothing at all

This is exactly what I am trying to avoid. I already know it has issues under certain circumstances so I can't actually say what features will or won't work. I don't want to say "this uses Lua File System" but have to add the caveat that it "may or may not work as expected". 

Since I've already built LuaScript with the lfs module then you are welcome to use it but this "may or may not work as expected" :)

[LuaScript.zip](https://github.com/dail8859/LuaScript/files/907698/LuaScript.zip)

This is a modified version of v0.6 that has the LuaFileSystem module. To use it you must call `require "lfs"` first.

Note that this does not mean I currently plan on including this in any future releases.

**Comment by ethanpil** [comment]
Have you seen this conversation?

http://lua.2524044.n2.nabble.com/LuaFileSystem-on-Windows-and-character-sets-td3581120.html

**Comment by dail8859** [comment]
I hadn't seen that one in particular, but it just reinforces the conclusion I originally came to. My main concern is that this discussion is from 7+ years ago and LFS still has this behavior...which means it probably isn't an easy fix.

**Comment by ethanpil** [comment]
Checking in... Just saw this and thought of this thread. :)
https://github.com/cloudwu/luawinfile

**Comment by dail8859** [comment]
I was actually looking into going ahead and including LFS but can't find the branch I was working on. I might take a look at luawinfile as an alternative.

**Comment by dail8859** [comment]
(Mostly note to self). Tried to compile luawinfile but it uses "variable length arrays" which VS 2015 does not support. So this would need to be converted to use dynamic memory allocation to compile cleanly
