### ISSUE TITLE
editor.AddText() doesn't work in OnModification

### ISSUE THREAD

**Issue by manake** [dail8859/LuaScript#81]
Is it possible to add text in `OnModification`?

```
function func1(ch)
    editor:AddText("works here")
end

function func2(modType, position, length, text, linesAdded)
    editor:AddText("doesn't work here")
end

npp.AddEventHandler("OnChar", func1)
npp.AddEventHandler("OnModification", func2)
```

**Comment by dail8859** [comment]
According to the [Scintilla documentation](https://www.scintilla.org/ScintillaDoc.html#SCN_MODIFIED):

> No modifications may be performed while in a SCN_MODIFIED event.

**Comment by manake** [comment]
Thanks!

(It's the first time I'm using this, I didn't know about this other documentation yet.)

**Comment by dail8859** [comment]
No problem. 

The plugin uses Lua to wrap all those Scintilla calls in an easier to use interface. So if you need specifics on a particular Scintilla feature then that documentation is the best reference.

Of course that doesnt cover this entire plugin since this plugin adds some of it's own features.
