### ISSUE TITLE
Error calling editor.GotoPos

### ISSUE THREAD

**Issue by StEngelhardt** [dail8859/LuaScript#91]
Hello Justin,

thank you for your great work!

I want to set the cursor of the current editor to a specific position (relative from start of file).

My code is

print("set pos to ".. oldPos)
print(type(oldPos))
editor.GotoPos(oldPos)

The output of the Lua interpreter is 

set pos to 2074
number
File:77: Self object is missing in pane method or property access.
stack traceback:
	[C]: in field 'GotoPos'
	File:77: in function <File:66>
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

What's wrong in my code? (I'm a Lua novice ;-))
Documentation says, the parameter should be a caret.
But I don't know, how to get a caret or if it is something else than a number.

Thank you 
Stefan

**Comment by dail8859** [comment]
Hi @StEngelhardt 

`GotoPos()` is a function of the `editor` object. To use this you need to use a colon rather than a period. For example:

```lua
editor:GotoPos(oldPos)
```

The `editor` object still has "properties" that still need to use a period (since it is treated like a variable). For example:

```lua
print(editor.LineCount)
```

These calling mechanisms aren't specific to LuaScript but the Lua language itself.

**Comment by StEngelhardt** [comment]
Thx Justin for the super fast answer ;-)

I have changed the period to a colon and now I no longer get exceptions.

```
	print("set pos to ".. oldPos)
	print(type(oldPos))
        editor:GotoPos(oldPos)
	print("GotoPos(".. oldPos .. ") called")
```

outputs 

```
set pos to 1043
number
GotoPos(1043) called
```

Unfortunately the caret of the current editor window is not moving to this position, but remains at the file beginning.

The complete function (without disturbing debug prints) looks like this

```
npp.AddEventHandler("OnOpen", function(filename, bufferid)
	readStateFile()
	local curFilename = string.upper(filename)
	local oldPos = cursorPosMap[curFilename] 
	if oldPos == nil then 
		print(curFilename .. " not in state file")
	else 
               editor:GotoPos(oldPos)
	end
end)
```
Any idea why the caret is not moving?

Cheers 
Stefan
```

**Comment by dail8859** [comment]
You aren't the first person to run across this issue. 

The official Scintilla documentation [addresses this behavior](https://www.scintilla.org/ScintillaDoc.html#LineWrapping):

> Wrapping is not performed immediately there is a change but is delayed until the display is redrawn. This delay improves performance by allowing a set of changes to be performed and then wrapped and displayed once. Because of this, some operations may not occur as expected. If a file is read and the scroll position moved to a particular line in the text, such as occurs when a container tries to restore a previous editing session, then the scroll position will have been determined before wrapping so an unexpected range of text will be displayed. To scroll to the position correctly, delay the scroll until the wrapping has been performed by waiting for an initial SCN_PAINTED notification.

This issue was also discussed on the [Notepad++ Community forum](https://community.notepad-plus-plus.org/topic/21517/python-gotoline-not-going-to-line-after-open). It was specifically about PythonScript but the underlying behavior is the same.

I'm not sure the best way to handle it. My first two ideas would be within the `OnOpen` to register to receive the `OnPainted` event, set the position within that handler, then have it remove itself. The simpler option might be to use a oneshot type of timer, see the [documentation](https://dail8859.github.io/LuaScript/classes/Notepad.html#Notepad.StartTimer). I'm not sure if there would be issues if you try to open multiple files at the same time (I would assume there would be) so not sure how to best handle that type of situation.

**Comment by StEngelhardt** [comment]
oneshot timer does the job ;-)

```
npp.AddEventHandler("OnOpen", 
function(filename, bufferid) 
	readStateFile()
	local curFilename = string.upper(filename)
	local oldPos = cursorPosMap[curFilename] 
	if oldPos == nil then 
		-- print(curFilename .. " not in state file")
	else 
            targetPos = oldPos
            npp.StartTimer(100, 
            function(timer) 
	   	editor:GotoPos(targetPos) 
                npp.StopTimer(timer) 
	    end)
	end
end)
```

BTW, I stucked on an old NP++ version, because I had an similiar functionality in Python Script, which is no longer supported. 
With your valuable help, I can switch now to the current NP++ version using a Lua based functionality ;-)

Thanks a lot!
