### ISSUE TITLE
Importing modules

### ISSUE THREAD

**Issue by Smurfy98** [dail8859/LuaScript#95]
Hello, today I compiled wxLua for use with this Npp plugin and it didn't work. The error I get is:

`error loading module 'wx' from file 'C:\Users\[USER]\AppData\Roaming\Notepad++\plugins\Config\LuaScriptLibs\wx.dll': The module could not be found`

I redacted my username and translated the part after the `:` because that was in my native language.

Do you have any idea how I could proceed with this? Is it just straight up not possible to load .dll files with this plugin? It does find the .dll, when I try to `require("wx")` without it being in the search path I get a different message. The .dll exports the funtion `luaopen_wx` and it works when using the Lua I also compiled for myself. So the problem will probably be either compatibility of the library (compiled using Lua 5.3.5 as a reference, just like your plugin) or the plugin itself.

Any help would be appreciated. Cheers.

**Comment by dail8859** [comment]
Hi @Smurfy98

Loading DLLs is possible. I don't use this myself but have had past users request this functionality.

> `error loading module 'wx' from file 'C:\Users\[USER]\AppData\Roaming\Notepad++\plugins\Config\LuaScriptLibs\wx.dll': The module could not be found`

Does this print file paths this is searching for? You can also modify where Lua searches for packages...I think it's `package.path` you can modify.

> Do you have any idea how I could proceed with this? Is it just straight up not possible to load .dll files with this plugin? It does find the .dll, when I try to `require("wx")` without it being in the search path I get a different message. The .dll exports the funtion `luaopen_wx` and it works when using the Lua I also compiled for myself. So the problem will probably be either compatibility of the library (compiled using Lua 5.3.5 as a reference, just like your plugin) or the plugin itself.

Since the dll is in that exact path then the DLL might not be compatible. There is an SDK on the releases page here on GitHub. If you compile wx with this lib then that should ensure the ABI matches.

Again I dont use this functionality myself so in theory there could be some issue introduced at some point which broke this.

**Comment by roman-orekhov** [comment]
I get exactly the same problem with any compatible DLLs. The dll file is in correct place but the error says it cannot be found anyway. The same DLL gets loaded by standalone lua53.exe with the same `package.cpath`

**Comment by OwnageIsMagic** [comment]
@roman-orekhov bitness mismatch?

**Comment by roman-orekhov** [comment]
@OwnageIsMagic NPP is 64 bit, plugin is 64 bit, its Lua is 64 bit and the DLLs I try to load are also 64 bit
