### ISSUE TITLE
feature_request: allow optionally compiling against luajit

### ISSUE THREAD

**Issue by insomnimus** [dail8859/LuaScript#97]
Hey, firstly thanks a lot for the plugin; it's really good!

I'm wondering if I could compile the plugin against luajit since it seems considerably faster, though I haven't had any performance issues so far.

I've been looking at the source but couldn't make a lot of progress so thought I'd ask.

Thanks.

**Comment by dail8859** [comment]
I'm not familiar with compiling against luajit. This project contains Lua in this folder here: https://github.com/dail8859/LuaScript/tree/master/src/lua

Not sure if it is as simple as replacing this version of Lua with luajit and then just make minimal changes from there.

Performance wise I'm not sure how impactful luajit would be. I'd assume in most nominal cases this plugin is used, that the majority of the time is spent inside the plugin DLL or within the Notepad++ process space. Though I can't say for certain since I'm not overly familiar with luajit.

**Comment by insomnimus** [comment]
I think it would be fair to assume repeated calls to callback functions would be faster since after some point luajit would have compiled them to machine code.

Alas, it's not really necessary since the plugin runs pretty smoothly.

Thank you for the response, I'll mess around more in my spare time and open another issue if the performance boost is significant.

**Comment by dail8859** [comment]
Under certain circumstances I'm sure luajit would perform better.

All I've ever known it to be used it for is miniscule compared to what Notepad++ is doing internally. So performance was never a concern in the past.
